version: "3.9"
services:
  postgres-db:
    image: postgres:13.2
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  web-server:
    build: .
    container_name: web-server
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - postgres-db
    volumes:
      - .:/app
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 80
